### ISSUE TITLE
Dashing issues with nextbus

### ISSUE THREAD

**Issue by jameswhite** [websages/dashboards-bnagh#40]
```
================================================================================
scheduler caught exception:
757: unexpected token at '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://nextbus.jt2k.com/api/findstop/36.162876,-86.78136?key=20e79a0133aece2ffea3b8aca42c782c">here</a>.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at nextbus.jt2k.com Port 80</address>
</body></html>
'
/var/lib/gems/2.1.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
/var/lib/gems/2.1.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
/home/opt/dashing/jobs/nextbus.rb:67:in `request'
/home/opt/dashing/jobs/nextbus.rb:39:in `nearby_stops'
/home/opt/dashing/jobs/nextbus.rb:15:in `block in <top (required)>'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
================================================================================
```
 
Cc: @stephenyeargin who might know an unemployed developer who could look at this.

**Comment by stephenyeargin** [comment]
https was added. Needs version bump.

--
Stephen Yeargin

**Comment by jameswhite** [comment]
nextbus or rufus needs a bump?

**Comment by stephenyeargin** [comment]
Nextbus, but I think that's inline code. I can PR or you can.

--
Stephen Yeargin

**Comment by jameswhite** [comment]
Appears https://github.com/websages/dashboards-bnagh/pull/39/commits/eb46ada382ed7aa88d1f8c54a91e8110549e4dbd got it.
